import type { Metadata } from "next";
import { Header } from "./header/Header";
import { LandingPage } from "../components/LandingPage/LandingPage";
import { Footer } from "./footer/Footer";

export const metadata: Metadata = {
  title: "SSDD",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
        <main className="">
          <Header />
          <LandingPage />
          <Footer />
        </main>
    </div>
  );
}
